[project]
name = "nanoom"
version = "0.1.0"
description = "balanced data splitting"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "jax",
    "polars>=1.36.1",
    "pulp>=3.3.0",
    "scikit-learn>=1.7.2",
]


[project.optional-dependencies]
cuda13 = [
    "jax[cuda13]",
]
chem = [
    "rdkit>=2025.3.6",
    "rich>=14.2.0",
    "bblean>=0.8.1",
]

dev = [
    "nanoom[chem]",
    "nanoom[cuda13]",
    "pytest",
    "ruff",
]
tutorial = [
    "marimo",
]


[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
